# Generated by Django 5.0.1 on 2024-08-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
