# Generated by Django 5.0.1 on 2024-09-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
