# Generated by Django 2.2 on 2024-09-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20240901_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_title', models.CharField(max_length=100)),
                ('not_content', models.TextField(max_length=100)),
            ],
        ),
    ]
