# Generated by Django 5.0.1 on 2024-09-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_contactmessage_id_alter_otp_id_and_more'),
        ('myapp', '0011_notificationmodel'),
    ]

    operations = [
    ]
