# Generated by Django 5.0.1 on 2024-10-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_merge_20240909_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
